default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: web_tools
  password: web_tools

development:
  <<: *default
  database: web_tools_development
  
test:
  <<: *default
  database: web_tools_test

production:
  <<: *default
  database: web_tools_production
  password: <%= ENV['RAILS-TEMPLATE_DATABASE_PASSWORD'] %>
